name = "TimeSchemes"
uuid = "d09d4d70-b71c-47d3-9b99-04be8bfefb18"
authors = ["cindea "]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"